### ISSUE TITLE
Fails to parse dependencies with extras_require like "adb-shell[async]"

### ISSUE THREAD

**Issue by antifuchs** [kk6/poetrify#122]
I've been trying to convert the requirements_all.txt for https://github.com/home-assistant/core, and poetrify is stumbling over [this line](https://github.com/home-assistant/core/blob/74053b5f2d953349a13e497c0e0c9fb610a632b2/requirements_all.txt#L105):

``` txt
# homeassistant.components.androidtv
adb-shell[async]==0.2.1
```

Running `poetrify generate -s requirements_all.txt` results in this error:
```
  HTTPError

  404 Client Error: Not Found for url: https://pypi.org/pypi/adb-shell%5Basync%5D/json/

  at /nix/store/7hh7s23ck1vc612x4yfc24dz9cl4qqm4-python3.8-requests-2.25.0/lib/python3.8/site-packages/requests/models.py:943 in raise_for_status
      939│         elif 500 <= self.status_code < 600:
      940│             http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
      941│
      942│         if http_error_msg:
    → 943│             raise HTTPError(http_error_msg, response=self)
      944│
      945│     def close(self):
      946│
      947│         called the underlying ``raw`` object must not be accessed again.
```

From what I can tell, the rules to use these packages with options in their dependencies are as follows:
* The real package name is stripped of `[.*]` - so, in the above case it's `adb-shell`
* The pyproject.toml dependency spec ends up being `adb-shell = {version = "0.2.1", extras = ["async"]}`

I guess using poetry's `add` command, I can work around this issue by just reading the requirements.txt line-by-line and adding the reqs - that seems to work pretty nicely in a tiny sample from those requirements_*.txt files; but it would be really nice if poetrify supported these lists natively.

**Comment by kk6** [comment]
@antifuchs 

Sorry for the late reply. I fixed it, please check it.

https://pypi.org/project/poetrify/
